apiVersion: v1
kind: Pod
metadata:
  name: posts
  labels:
    name: posts-app
spec:
  containers:
    - name: posts
      image: bdomingo/posts:0.0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4000
